version: "3.8"

services:
  backend:
    build: ./backend
    container_name: sacred6-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/sacred6
      # For container-to-container communication
      - FRONTEND_URL=http://frontend:3000
      # For external access
      - CORS_ORIGIN=http://localhost:3000,https://sacred6.ams8.nl
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: sacred6-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # For browser clients (must be the external URL)
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
